default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_user: <%= ENV["ADMIN_USER"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
